### ISSUE TITLE
Highlight problem with Treesitter on YAML files using your color theme

### ISSUE THREAD

**Issue by mengano-net** [LunarVim/darkplus.nvim#15]
I’m a long time consumer of your Neovim content on youtube, great job and thanks for making your time available so that we all have a better editor.

I work on yaml(AWS CloudFormation) a lot, been having a problem with darkplus color theme: Treesitter doesn’t seem to set highlights correctly with your color theme (at least I think so)

… I hope you can help me. I also added a new issue on your github repo: 

- On file ~/.local/share/nvim/site/pack/packer/start/darkplus.nvim/colors/darkplus.vim, you have:

hl(0, "yamlPlainScalar", { fg = c.orange, bg = 'NONE' })
hl(0, "yamlTSField", { fg = c.blue, bg = 'NONE' })

… then on you palette file, you have:
  blue = "#569CD6",
  orange = "#CE9178",

- On neovim, after having set “:colorscheme darkplus” and opened a yaml buffer, I see:

:hi yamlPlainScalar
yamlPlainScalar xxx guifg=#ce9178

:hi yamlTSField
yamlTSField    xxx guifg=#569cd6

- … But I actually see [this](https://imgur.com/a/uUXDrFY)
- … however, if I disable Treesitter highlights with ‘:TSBufDisable highlight’, then I get [correct] hightlights (https://imgur.com/a/BTmI9my) colors.

**Comment by gutyina70** [comment]
Looks like this is caused by a typo: TSField highlight should link to Var**i**able, not Varable.

**Comment by mengano-net** [comment]
Oh, thanks for the fix! Again, I'm bitten by typos that I keep missing :(
Thanks again! It was great to see you fixing my issue live on your telecast 👍
