### ISSUE TITLE
colors ares bit buggy on replace mode for lualine

### ISSUE THREAD

**Issue by A7Lavinraj** [LunarVim/darkplus.nvim#27]
## Is this related to darkplus colorscheme?
Yes, it is because lualine colors are all good with colorscheme

## screenshot
![Screenshot from 2023-11-06 23-05-48](https://github.com/LunarVim/darkplus.nvim/assets/107323410/090f8acb-f37a-49b2-b8cb-3e4769fcd3db)

## How to reproduce the bug?
- open neovim.
- set colorscheme to [darkplus.nvim](https://github.com/LunarVim/darkplus.nvim).
- enter in replace mode with `shift-r`.
- look at [lualine](https://github.com/nvim-lualine/lualine.nvim) modes.

## How to fix?

just change the color of lualine for replace mode to red or something that is visible

**Comment by gepbird** [comment]
I can reproduce this issue and found the cause: for the lualine theme a `red1` color was declared, but for replace mode `red` is used which is undefined (see https://github.com/LunarVim/darkplus.nvim/blob/master/lua/lualine/themes/darkplus.lua#L5).
