### ISSUE TITLE
After update getting an error in one of the functions

### ISSUE THREAD

**Issue by bab014** [LunarVim/darkplus.nvim#9]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/61920876/182656416-6b0f5939-8a3e-4547-9a32-4b250724d278.png">

Very new to Neovim and not sure if this is something I need to update in my config or if it's actually a bug

**Comment by eaparnell** [comment]
I am getting the same error. Can't find the commit where it was introduced but probably within 24 hours since I typically update by plugins often.

**Comment by eaparnell** [comment]
Not sure why **underdotted**  is not being recognized. Changed it to underline and it works.
Running on Mac, here is my version info.
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
Features: +acl +iconv +tui

BTW, thanks for all your hard work -- I really enjoy the theme.

**Comment by tomiwaorimoloye** [comment]
I did what you did what you did and it worked.
I'm curious to what changing underdotted to underline actually does and how you knew the word underline would work?

**Comment by eaparnell** [comment]
Well, looking at the code this seems to annotate markdown links. I think "underdotted" is a dotted underline whereas "underline" is a solid underline. This indeed may be a neovim bug where "underdotted" is not implemented but I will leave that to the developers here.
The neovim api can be found here: [api](https://neovim.io/doc/user/api.html).
In it, there is the `nvim_set_hl` function which documents the "underline" attribute. That's basically how I knew it would work, other than testing it out. Note "underdotted" is there too which makes me think there is a bug.

Full disclosure: While I am new to nvim/lua, I have been a developer for many years so the experience doesn't hurt :)

**Comment by gutyina70** [comment]
Looks like [this change](https://github.com/neovim/neovim/pull/19159) in neovim caused this issue, which is not in neovim version 0.7.2, but only in nightly.

**Comment by gutyina70** [comment]
@bab014 @eaparnell @tomiwaorimoloye should be fixed if you update this plugin.
@bab014 please close this issue if you feel like it is solved.

**Comment by eaparnell** [comment]
It is working now. Thank you!
